export const enOnboarding = {
  skip: "Explore now", back: "Back", next: "Continue", start: "Make yourself at home", login: "Already a member? Sign in", language: "Language",
  progress: "Step {{current}} of {{total}}", welcomeKicker: "A little inspiration. A lot of flavour.",
  welcomeTitle: "Good food starts with what you have.", welcomeText: "Meet Alf Sahten: recipes from real cooks, a kitchen that starts with your ingredients, and favourites worth coming back to.",
  pantryChip: "Your ingredients", inspirationChip: "Fresh ideas", favouritesChip: "Recipes to keep",
  goalsKicker: "Your kitchen, your pace", goalsTitle: "What would make cooking easier?", goalsText: "Pick a starting point. You can explore everything whenever you like.",
  pantry: "Make more of what I have", pantryText: "Start with the ingredients already in your kitchen.", quick: "Find everyday inspiration", quickText: "Discover dishes for the meals you cook most often.", explore: "Try something different", exploreText: "Meet new cooks and explore Lebanese favourites.", save: "Keep my favourites together", saveText: "Save recipes you want to cook again.",
  readyKicker: "Pull up a chair", readyTitle: "Where shall we start?", readyText: "Choose your first stop. No account is needed to browse recipes or try My Kitchen.",
  kitchen: "Open My Kitchen", kitchenText: "Add a few ingredients and see what you could cook.", discover: "Browse recipes", discoverText: "Explore dishes and the cooks behind them.", saved: "Build your favourites", savedText: "Sign in to keep saved recipes in one place.", recommended: "Suggested for you", localNote: "This welcome is remembered in this browser.",
};
export const frOnboarding: Record<keyof typeof enOnboarding, string> = {
  skip: "Explorer maintenant", back: "Retour", next: "Continuer", start: "Bienvenue chez vous", login: "Déjà membre ? Se connecter", language: "Langue",
  progress: "Étape {{current}} sur {{total}}", welcomeKicker: "Un peu d’inspiration. Beaucoup de saveur.", welcomeTitle: "Bien manger commence avec ce que vous avez.", welcomeText: "Découvrez Alf Sahten : les recettes de vrais cuisiniers, une cuisine qui part de vos ingrédients et des favoris à retrouver.",
  pantryChip: "Vos ingrédients", inspirationChip: "De nouvelles idées", favouritesChip: "Recettes à garder", goalsKicker: "Votre cuisine, votre rythme", goalsTitle: "Qu’est-ce qui faciliterait vos repas ?", goalsText: "Choisissez un point de départ. Tout reste accessible à tout moment.",
  pantry: "Utiliser ce que j’ai déjà", pantryText: "Commencez avec les ingrédients de votre cuisine.", quick: "Trouver des idées au quotidien", quickText: "Découvrez des plats pour vos repas de tous les jours.", explore: "Essayer quelque chose de nouveau", exploreText: "Rencontrez des cuisiniers et découvrez les saveurs libanaises.", save: "Rassembler mes favoris", saveText: "Gardez les recettes que vous souhaitez refaire.",
  readyKicker: "Prenez place", readyTitle: "Par où commencer ?", readyText: "Choisissez votre première étape. Parcourez les recettes et essayez Ma cuisine sans compte.", kitchen: "Ouvrir Ma cuisine", kitchenText: "Ajoutez quelques ingrédients et découvrez quoi cuisiner.", discover: "Parcourir les recettes", discoverText: "Explorez les plats et leurs cuisiniers.", saved: "Créer mes favoris", savedText: "Connectez-vous pour retrouver vos recettes enregistrées.", recommended: "Suggestion pour vous", localNote: "Cet accueil est mémorisé dans ce navigateur.",
};
export const arOnboarding: Record<keyof typeof enOnboarding, string> = {
  skip: "استكشف الآن", back: "رجوع", next: "متابعة", start: "أهلًا فيك", login: "عندك حساب؟ سجّل الدخول", language: "اللغة",
  progress: "الخطوة {{current}} من {{total}}", welcomeKicker: "شوية إلهام. كتير نكهة.", welcomeTitle: "الأكل الطيّب بيبلّش بالموجود عندك.", welcomeText: "تعرّف على ألف صحتين: وصفات من طهاة حقيقيين، أفكار بتبلّش بمكوّنات مطبخك، ووصفات بتحب ترجع إلها.", pantryChip: "مكوّناتك", inspirationChip: "أفكار جديدة", favouritesChip: "وصفات بتحبّها",
  goalsKicker: "مطبخك، على راحتك", goalsTitle: "شو بيسهّل عليك الطبخ؟", goalsText: "اختار من وين تبلّش. فيك تستكشف كل شي بأي وقت.", pantry: "استفيد من الموجود عندي", pantryText: "بلّش بالمكوّنات الموجودة بمطبخك.", quick: "لاقي أفكار للأكل اليومي", quickText: "اكتشف أطباق بتناسب وجباتك اليومية.", explore: "جرّب شي جديد", exploreText: "تعرّف على طهاة واكتشف نكهات لبنانية.", save: "اجمع وصفاتي المفضّلة", saveText: "احفظ الوصفات اللي بدّك ترجع تطبخها.",
  readyKicker: "تفضّل معنا", readyTitle: "من وين منبلّش؟", readyText: "اختار أول محطة. ما بدّك حساب لتتصفّح الوصفات أو تجرّب مطبخي.", kitchen: "افتح مطبخي", kitchenText: "أضف كم مكوّن وشوف شو فيك تطبخ.", discover: "تصفّح الوصفات", discoverText: "اكتشف الأطباق والطهاة اللي وراها.", saved: "اجمع وصفاتك المفضّلة", savedText: "سجّل الدخول لتحتفظ بوصفاتك بمكان واحد.", recommended: "اقتراح إلك", localNote: "منحفظ هالترحيب بهالمتصفّح.",
};
