create table if not exists public.kitchen_ingredients (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  ingredient_name text not null check (char_length(trim(ingredient_name)) > 0),
  created_at timestamptz not null default now()
);

create unique index if not exists kitchen_ingredients_user_name_unique
  on public.kitchen_ingredients (user_id, lower(trim(ingredient_name)));

alter table public.kitchen_ingredients enable row level security;

drop policy if exists "Users can view own kitchen ingredients" on public.kitchen_ingredients;
create policy "Users can view own kitchen ingredients"
on public.kitchen_ingredients
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can add own kitchen ingredients" on public.kitchen_ingredients;
create policy "Users can add own kitchen ingredients"
on public.kitchen_ingredients
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can delete own kitchen ingredients" on public.kitchen_ingredients;
create policy "Users can delete own kitchen ingredients"
on public.kitchen_ingredients
for delete
to authenticated
using (auth.uid() = user_id);

grant select, insert, delete on public.kitchen_ingredients to authenticated;
grant usage, select on sequence public.kitchen_ingredients_id_seq to authenticated;
